# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mlwx7sitKy0FRn1hlmDem64YYDYX2zN8
"""

import numpy as np
arr=np.array([[1,2,3],[4,2,5]])
print("array is of type:",type(arr))
print("number of dimensions(axes):",arr.ndim)
print("shape of array:",arr.shape)
print("array stores elements of type:",arr.dtype)

import numpy as np
array1=np.array([1.2,2.5,2.8,3.9])
print(array1)
array2=np.zeros([3,4])
print(array2)
array3=np.array((11,22,33,44,55))
print(array3)
array4=np.random.randint(10,75,(2,2))
print(array4)

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(3,4)
arr2=arr1.reshape(2,2,3)
print(arr2)
arr3=np.arange(start=0,stop=30,step=5)
print(arr3)
arr4=np.array([[2,3],[4,5]])
print(arr4.flatten())
arr5=np.full((2,3),60,dtype=complex)
print(arr5)