# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebCvSmMdsPlYKg6ih4Q7P0ZnkkEqfyN2
"""

f=open("abc.txt","w")
f.write("hello world")
f.close()
f=open("abc.txt","r")
print(f.read())
f.close()

f=open("abc.txt","a")
f.write("\nhi python programming")
f.close()
f=open("abc.txt","r")
print(f.read())
f.close()

print("one")
print("two")
print("three")
print(10/0)
print("four")
print("five")

def divide(x,y):
  try:
    result=x/y
  except ZeroDivisionError:
    print("sorry!!dividing by zero")
  else:
    print("your answer is:",result)
  finally:
    print("this is always executed")
divide(3,2)
divide(5,0)