# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGRR2mdh5HV0TdjNQds6Ms68TUap-eK4
"""

a=int(input("enter any number"))
b=int(input("enter another number"))
c=a+b
print("sum of two numbers=",c)

a=int(input("enter any number"))
if a>0:
  print("positive number")
else:
  print("negative number")

a=int(input("enter a's value"))
b=int(input("enter b's value"))
c=int(input("enter c's value"))
if (a>b)and(a>c):
  print("a is greater",a)
elif (b>a)and(b>c):
  print("b is greater",b)
else:
  print("c is greater",c)

x=int(input("enter any number between 1 to 7"))
if (x==1):
  print("monday")
elif (x==2):
  print("tuesday")
elif (x==3):
  print("wednesday")
elif (x==4):
  print("thursday")
elif (x==5):
  print("friday")
elif (x==6):
  print("saturday")
else:
  print("sunday")

set1={"apple","banana","cherry","mango"}
print(set1)
set1.add("lemon")
print(set1)
set1.remove("apple")
print(set1)
x=set1.copy()
print(x)

dicts={(0,1,2,'hello'):100,(1,2,3):200}
print(dicts)

