# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cCBbNLagG-2C5Em73ZeiEfuy4qj641m
"""

class display:
  def method(self):
    print("welcome to MRCET")
obj=display()
obj.method()

class person:
  age=10
  def greet(self):
    print("hello")
obj=person()    
print(obj.age)
obj.greet()

class test:
  def sum(self,a,b):
    s=a+b
    return s
a=int(input("enter first number"))
b=int(input("enter second number"))
obj=test()
s1=obj.sum(a,b)
print("sum is:",s1)

class marks:
  def find(self,m1,m2,m3):
    s=m1+m2+m3
    t=(s/75)*100
    if t>40:
      print("pass")
    else:
      print("fail")
m1=int(input("enter marks of 1 subject"))
m2=int(input("enter marks of 2 subject"))
m3=int(input("enter marks of 3 subject"))
obj=marks()
obj.find(m1,m2,m3)

