# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdB05SSopFU2TcGOArs4tuDgvwSd8ynK
"""

import sys
print("python version")
print(sys.version)
print("version info.")
print(sys.version_info)

f1=open("abc.txt","w")
f1.write("hello python")
f1.close()
import os
import sys
p1=os.access("abc.txt",os.F_OK)
print("exists the path:",p1)
p2=os.access("abc.txt",os.R_OK)
print("access to read the file:",p2)
p3=os.access("abc.txt",os.W_OK)
print("access to write the file:",p3)
p4=os.access("abc.txt",os.X_OK)
print("check if path can be executed:",p4)

import calendar
yy=int(input("enter year:"))
mm=int(input("enter month:"))
print(calendar.month(yy,mm))

import calendar
def printcal(year):
  print(calendar.calendar(year))
year=2021
printcal(year)

import datetime
a=datetime.datetime.today()
b=datetime.datetime.now()
print(a)
print(b)

from datetime import datetime
from datetime import timedelta
from datetime import date
begindate=date.today()
print("beginning date:")
print(begindate)
enddate=begindate+timedelta(days=4)
print("ending date:")
print(enddate)

from math import pi
r=float(input("enter radius:"))
print("the area of circle with radius ",r," is ",(pi*r**2))