# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgitg1JuUicP8hurycGVCvjICRGpgN0M
"""

x={'apple':28,'mango':35,'grape':23,'banana':15}
print(x)

#length
print(len(x))

#access                        
print(x.keys())
print(x.values())
print(x.items())

#get
y=x.get('mango')
print(y)

x=[5,3,7,9]
#insert
x.insert(1,9)
print(x)
x.insert(2,['k','a','v'])
print(x)

#remove
x.remove(9)
print(x)

#append
x.append(7)
print(x)

#length
print(len(x))

#pop
x.pop()
print(x)
print(x.pop())

#clear
x.clear()
print(x)

t=(1,10,20,'hello')
#add 
#t[1]=5
print(t)

#length
print(len(t))

#check for any item
print(any(t))

#access
print(t[0])
print(t[1:3])